#!/usr/bin/env bash

gnome-terminal --tab -- roscore

sleep 2s

gnome-terminal --tab --command="bash -c 'source $(pwd)/devel/setup.sh;
export MESH_WORKSPACE_PATH=$(pwd)/models;
export GAZEBO_MODEL_PATH=$(pwd)/models;
roslaunch $(pwd)/src/baxter_moveit/baxter_moveit/launch/execution_stick.launch; $SHELL'"

sleep 2s

gnome-terminal --tab --command="bash -c 'source $(pwd)/devel/setup.sh
export MESH_WORKSPACE_PATH=$(pwd)/models
export GAZEBO_MODEL_PATH=$(pwd)/models
python $(pwd)/Persistent_Homology/spawn_config.py; $SHELL'"
