#!/usr/bin/env bash

gnome-terminal --tab -- roscore

sleep 10s

gnome-terminal --tab --command="bash -c 'source $(pwd)/devel/setup.sh;
export MESH_WORKSPACE_PATH=$(pwd)/models;
export GAZEBO_MODEL_PATH=$(pwd)/models;
source ./simulation_commands/1_open_gazebo; $SHELL'"

sleep 50s

gnome-terminal --tab --command="bash -c 'source $(pwd)/devel/setup.sh
export MESH_WORKSPACE_PATH=$(pwd)/models
export GAZEBO_MODEL_PATH=$(pwd)/models
source ./simulation_commands/2_enable_robot; $SHELL'"

sleep 10s

gnome-terminal --tab --command="bash -c 'source $(pwd)/devel/setup.sh
export MESH_WORKSPACE_PATH=$(pwd)/models
export GAZEBO_MODEL_PATH=$(pwd)/models
source ./simulation_commands/3_open_moveit; $SHELL'"

# sleep 10s

# gnome-terminal --tab --command="bash -c 'source $(pwd)/devel/setup.sh
# export MESH_WORKSPACE_PATH=$(pwd)/models
# export GAZEBO_MODEL_PATH=$(pwd)/models
# source ./simulation_commands/4_perception; $SHELL'"
