# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: motoman_robotiq_hand
  joint_model_group_pose: motoman_robotiq_hand_home_config
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - torso_joint_b1
    - arm_left_joint_1_s
    - arm_left_joint_2_l
    - arm_left_joint_3_e
    - arm_left_joint_4_u
    - arm_left_joint_5_r
    - arm_left_joint_6_b
    - arm_left_joint_7_t
    - arm_right_joint_1_s
    - arm_right_joint_2_l
    - arm_right_joint_3_e
    - arm_right_joint_4_u
    - arm_right_joint_5_r
    - arm_right_joint_6_b
    - arm_right_joint_7_t
    - finger_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  []