#!/usr/bin/env bash
source $(pwd)/devel/setup.sh
export MESH_WORKSPACE_PATH=$(pwd)/models
export GAZEBO_MODEL_PATH=$(pwd)/models

roslaunch $(pwd)/src/baxter_moveit/baxter_moveit/launch/execution.launch
