#!/usr/bin/env python

import sys
import copy
from math import pi, tau
from random import uniform, choice

import numpy as np

import rospy
from tf.transformations import *
# from geometry_msgs.msg import Twist
from gazebo_msgs.msg import ModelStates, ModelState
from moveit_commander.conversions import *

init_states_pub = None
updatePeriod = 0.5
lastUpdateTime = None
count = 0

ignore = {'ground_plane', 'table', 'baxter'}
directions = {
    'cylinder_red': [choice([0, tau / 4]), 0, choice(np.linspace(0, tau, 9)[:-1])],
    'cylinder_blue': [choice([0, tau / 4]), 0, choice(np.linspace(0, tau, 9)[:-1])],
    'stone_10_2_5_1cm_0': [0, choice([0, tau / 4]), choice(np.linspace(0, tau, 9)[:-1])],
    'round_tin_base': [choice([0, tau / 4]), 0, choice(np.linspace(0, tau, 9)[:-1])],
    'wood_cube': [0, 0, choice(np.linspace(0, tau, 9)[:-1])],
    'plastic_cup': [choice([0, tau / 4]), 0, choice(np.linspace(0, tau, 9)[:-1])],
}


def on_model_states_msg(msg):
    global lastUpdateTime
    global count
    sinceLastUpdateDuration = rospy.get_rostime() - lastUpdateTime
    if sinceLastUpdateDuration.to_sec() < updatePeriod:
        return
    lastUpdateTime = rospy.get_rostime()

    if count > 1:
        return
    else:
        count += 1

    for (model_name, model_pose) in zip(msg.name, msg.pose):
        if model_name not in ignore:
            print(model_name)
            print(model_pose)
            new_msg = ModelState()
            new_msg.model_name = model_name
            new_msg.reference_frame = "world"
            new_msg.pose = copy.deepcopy(model_pose)
            new_msg.pose.orientation
            # x = choice(np.linspace(tau, -tau, 9)[:-1])
            # y = choice(np.linspace(tau, -tau, 9)[:-1])
            # z = choice(np.linspace(tau, -tau, 9)[:-1])
            print(directions[model_name])
            q = quaternion_from_euler(*directions[model_name])
            new_msg.pose.orientation.x = q[0]
            new_msg.pose.orientation.y = q[1]
            new_msg.pose.orientation.z = q[2]
            new_msg.pose.orientation.w = q[3]
            new_msg.pose.position.z += 0.05
            print(new_msg)
            init_states_pub.publish(new_msg)


def main():
    rospy.init_node('gazebo_rand_instance')

    global init_states_pub
    init_states_pub = rospy.Publisher('/gazebo/set_model_state', ModelState, queue_size=10)
    # rospy.sleep(rospy.Duration(0, 100 * 1000))

    global lastUpdateTime
    lastUpdateTime = rospy.get_rostime()
    modelStatesSub = rospy.Subscriber('/gazebo/model_states', ModelStates, on_model_states_msg)
    # msg = rospy.wait_for_message('/gazebo/model_states', ModelStates)
    # rospy.sleep(rospy.Duration(0, 100 * 1000))

    # rospy.loginfo('Spinning')
    while count < 2:
        rospy.Rate(10).sleep()
    # rospy.spin()


if __name__ == '__main__':
    main()
