controller_list:
  - name: /robot/limb/right
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - right_s0
      - right_s1
      - right_e0
      - right_e1
      - right_w0
      - right_w1
      - right_w2
  - name: /robot/limb/left
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - left_s0
      - left_s1
      - left_e0
      - left_e1
      - left_w0
      - left_w1
      - left_w2
  # - name: /robot/end_effector/left_gripper
  #   action_ns: gripper_action
  #   type: GripperCommand
  #   default: true
  #   parallel: true
  #   joints:
  #     - l_gripper_l_finger_joint
  #     - l_gripper_r_finger_joint
  # - name: /robot/end_effector/right_gripper
  #   action_ns: gripper_action
  #   type: GripperCommand
  #   default: true
  #   parallel: true
  #   joints:
  #     - r_gripper_l_finger_joint
  #     - r_gripper_r_finger_joint
